/*=============== CHANGE THE LANGUAGE ====================*/
var data = {
    "english": 
    {
        "mainDesc": "Comprehensive solutions for the aviation industry.",
        "stronaMenu": "Main Page",
        "projektyMenu": "Key Projects",
        "uslugiMenu": "Services",
        "kontaktMenu": "Contact",
        "naglowek": "About us...",
        "dynamicznie": "Savicon is a dynamically developing company. We have many years of experience with clients from the aviation, cargo, KEP and postal industries. We offer a wide range of solutions worldwide, such as:",
        "tekst1": "• BHS (Baggage handling systems) - Transport of checked baggage",
        "tekst2": "• Sortation systems - sorting parcels and luggage",
        "tekst3": "• EBS (Early baggage storage) - early checked baggage storage",
        "tekst4": "• Conveyors and carousels - conveyor belts and luggage collection carousels",
        "tekst5": "• Security screening - luggage screening devices",
        "tekst6": "• Checkpoint Screening - personal control points", 
        "projekty": "Key projects",
        "aa": "Realisation period:",
        "bb": "Realisation period:",
        "cc": "Realisation period:",
        "dd": "Realisation period:",
        "ee": "Realisation period:",
        "daty1": "2017 - up to now",
        "daty2": "2020 - up to now",
        "daty3": "2021 - up to now",
        "services": "Services",
        "zakresUslug": "Scope Of Services", 
        "opisUslug": "The scope of our services covers problems related to the functioning of airports focusing on the most effective sorting of luggage.",
        "koncepcja": "Concept and design", 
        "opisKoncepcji": "We advise on the most optimal solutions at the concept stage, which we turn into a comprehensive multi-industry project.",
        "wykonawstwo": "Execution",
        "opisWykonawstwa": "We comprehensively perform electrical, teletechnical and mechanical installations in accordance with agreed designs.", 
        "utrzymanie": "Maintenance", 
        "opisUtrzymania": "We maintain strategic systems with a rapid response time tailored to the client's requirements. We provide 24/7 support throughout Poland and Europe.", 
        "kontakt": "Contact",
        "kontakt1": "Contact",
        "biuro": "Our office",
        "daneFirmy": "Company info", 
        "mapaTytul": "Map of our projects", 
        "europa": "Europe",
        "ameryka": "America"
    
        
    }, 
    "kazakh": 
	{
        "mainDesc": "Kompleksowe rozwiązania dla branży lotniczej.",
        "stronaMenu": "Strona główna",
        "projektyMenu": "Kluczowe projekty",
        "uslugiMenu": "Usługi",
        "kontaktMenu": "Kontakt",
        "naglowek": "O nas...",
        "dynamicznie": "Dynamicznie rozwijająca się firma Savicon. Posiadamy wieloletnie doświadczenie z klientami z branży lotniczej, cargo, KEP i pocztowych. Oferujemy szeroki wachlarz usług rozwiązań na całym swiecie takich jak:",
        "tekst1": "• BHS (Baggage handling systems) - Transport bagażu rejstrowanego",
        "tekst2": "• Sortation systems - sortowanie paczek, bagaży",
        "tekst3": "• EBS (Early baggage storage) - magazyn bagażu wcześnie odprawionego",
        "tekst4": "• Conveyors and carousels - tasmociagi transportowe i karuzele odbioru bagaży",
        "tekst5": "• Security screening - urzadzenia prześwietlające bagaż",
        "tekst6": "• Checkpoint Screening - punkty kontroli osobistej",
        "projekty": "Kluczowe projekty",
        "aa": "Data realizacji:",
        "bb": "Data realizacji:",
        "cc": "Data realizacji:",
        "dd": "Data realizacji:",
        "ee": "Data realizacji:",
        "daty1": "2017 - obecnie",
        "daty2": "2020 - obecnie",
        "daty3": "2021 - obecnie",
        "services": "Usługi",
        "zakresUslug": "Zakres usług", 
        "opisUslug": "Zakres naszych usług obejmuje problemy związane z funkcjonowaniem portów lotniczych skupiające się na najefektywniejszym sortowaniu bagaży.", 
        "koncepcja": "Koncepcja i projektowanie",
        "opisKoncepcji": "Doradzamy na etapie koncepcji najbardziej optymalne rozwiązania które przekuwamy w kompleksowy projekt wielobranżowy.",
        "wykonawstwo": "Wykonawstwo", 
        "opisWykonawstwa": "Kompleksowo wykonujemy instalacje elektryczne, teletechniczne i mechaniczne zgodnie z ustalonymi projektami.", 
        "utrzymanie": "Utrzymanie", 
        "opisUtrzymania": "Utrzymujemy strategiczne systemy z błyskawicznym czasem reakcji dopasowanym do wymogów klienta. Zapewniamy wsparcie 24/7 na terenie całej Polski i Europy.", 
        "kontakt": "Contact",
        "kontakt1": "Contact",
        "biuro": "Nasze biuro",
        "daneFirmy": "Dane firmy", 
        "mapaTytul": "Mapa realizacji", 
        "europa": "Europa",
        "ameryka": "Ameryka"
        
    }
    
}
